obj-$(CONFIG_ARCH_GK7102C) += gk7102c.o
obj-$(CONFIG_ARCH_GK7102C) += irq.o
obj-$(CONFIG_ARCH_GK7102C) += rct.o
obj-$(CONFIG_ARCH_GK7102C) += mdma.o dma.o
obj-$(CONFIG_ARCH_GK7102C) += vi.o
obj-$(CONFIG_ARCH_GK7102C) += mach-gk7102c.o

ccflags-$(CONFIG_ARCH_GK7102C) += -D__LINUX__ 

ccflags-$(CONFIG_ARCH_GK7102C) += -Iarch/arm/mach-gk7102c/include

obj-$(CONFIG_ARCH_GK7102C_FPGA) += gk7102c.o
obj-$(CONFIG_ARCH_GK7102C_FPGA) += irq.o
obj-$(CONFIG_ARCH_GK7102C_FPGA) += rct.o
obj-$(CONFIG_ARCH_GK7102C_FPGA) += mdma.o dma.o
obj-$(CONFIG_ARCH_GK7102C_FPGA) += vi.o
obj-$(CONFIG_ARCH_GK7102C_FPGA) += mach-gk7102c.o
ccflags-$(CONFIG_ARCH_GK7102C_FPGA) += -D__LINUX__ 
ccflags-$(CONFIG_ARCH_GK7102C_FPGA) += -Iarch/arm/mach-gk7102c/include
